import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/shared/components/layout";
import Footer from "@/shared/components/layout/Footer";
import ProviderClient from "@/core/infrastructure/services/ProviderClient";
import CartInitializer from "@/features/cart/components/CartInitializer";
import UserInitializer from "@/shared/components/auth/UserInitializer";
import { Toaster } from "@/shared/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProviderClient>
          <UserInitializer />
          <CartInitializer />
          <Navbar />
          {children}
          <Footer />
          <Toaster />
        </ProviderClient>
      </body>
    </html>
  );
}
