import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/styles/themes/theme1/development.css";
import Navbar from "@/components/layout/index";
import Footer from "@/components/layout/Footer";
import CartInitializer from "@/features/cart/components/CartInitializer";
import { Toaster } from "@/shared/components/ui/sonner";
import ProviderClient from "@/store/ProviderClient";
import UserInitializer from "@/features/auth/components/UserInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProviderClient>
          <UserInitializer />
          <CartInitializer />
          <Navbar />
          {children}
          <Footer />
          <Toaster />
        </ProviderClient>
      </body>
    </html>
  );
}
